<template>
    <section id="about">
        <div>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
            I am about<br/>
        </div>
    </section>
</template>